apiVersion: v2
appVersion: 2.3.2
description: A Helm chart for paperless-ngx
name: paperless-ngx
type: application
version: 0.1.0
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    version: 9.16.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    version: 13.2.28
