apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benotes.fullname" . }}
  labels:
    {{- include "benotes.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "benotes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "benotes.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "benotes.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Fix for permissions issue
      {{- if .Values.persistence.enabled }}
      initContainers:
        - name: fix-permissions
          image: php:8.1-fpm-alpine
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.path }}
          command:
            - /bin/sh
            - -c
            - |
              cd {{ .Values.persistence.path }}
              mkdir -p framework/sessions framework/views framework/cache
              chown -R www-data:www-data {{ .Values.persistence.path }} && chmod -R 774 {{ .Values.persistence.path }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef: 
                name: {{ include "benotes.fullname" . }}
          env:
            {{- if and .Values.sqlite.enabled (not .Values.externalDbUrl) }}
            - name: DB_CONNECTION
              value: sqlite
            - name: DB_DATABASE
              value: /var/www/storage/{{ .Values.sqlite.dbPath }}
            {{- end }}
            - name: APP_PORT
              value: {{ .Values.service.port | quote }}
            - name: CACHE_DRIVER
              value: {{ .Values.config.cacheDriver }}
            - name: USE_FILESYSTEM
              value: "true"
            - name: APP_TIMEZONE
              value: {{ .Values.config.appTz }}
            - name: APP_ENV
              value: {{ .Values.config.appEnv }}
            - name: APP_DEBUG
              value: {{ .Values.config.appDebug | quote }}
            {{- range .Values.extraEnv }}
            {{- if and (.name) (.value) }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.path }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "benotes.pvcName" . }}
      {{- end }} 
