apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benotes.fullname" . }}
  labels:
    {{- include "benotes.labels" . | nindent 4 }}
data:
  APP_KEY: 
  JWT_SECRET: 
  DB_CONNECTION: 
  DB_HOST: 
  DB_DATABASE:
  DB_USERNAME: 
  DB_PASSWORD: 
  {{- if .Values.mail.enabled }}
  MAIL_USERNAME:
  MAIL_PASSWORD: 
  MAIL_HOST:
  MAIL_FROM_ADDRESS:
  {{- end }}