apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benotes.fullname" . }}
  labels:
    {{- include "benotes.labels" . | nindent 4 }}
data:
  APP_KEY: {{ default (randAlphaNum 32) .Values.appKey | b64enc }}
  JWT_SECRET: {{ default (randAlphaNum 32) .Values.jwtSecret | b64enc }}
  {{- if not .Values.sqlite.enabled and not .Values.externalDbUrl }}
  DB_HOST: {{- if .Values.postgresql.enabled }} {{ "%s-postgresql" .Release.Name | b64enc }} {{- else }} {{ "%s-mysql" .Release.Name | b64enc }} {{- end }}
  DB_PORT: {{- if .Values.postgresql.enabled }} {{ "5432" | b64enc }} {{- else }} {{ "3306" | b64enc }} {{- end }}
  DB_USERNAME: {{- if .Values.postgresql.enabled }} {{ .Values.postgresql.auth.username | b64enc }} {{- else }} {{ .Values.mysql.auth.username | b64enc }} {{- end }}
  DB_PASSWORD: {{- if .Values.postgresql.enabled }} {{ .Values.postgresql.auth.password | b64enc }} {{- else }} {{ .Values.mysql.auth.password | b64enc }} {{- end }}
  {{- end }}
  {{- if .Values.mail.enabled }}
  MAIL_USERNAME: {{ .Values.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
  MAIL_HOST: {{ .Values.mail.host | b64enc }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.fromAddress | b64enc}}
  {{- end }}