apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benotes.fullname" . }}
  labels:
    {{- include "benotes.labels" . | nindent 4 }}
data:
  APP_KEY: {{ .Values.config.appKey | b64enc }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc }}
  CACHE_DRIVER: {{ .Values.config.cacheDriver | b64enc }}
  {{- if and (not .Values.sqlite.enabled) (not .Values.externalDbUrl) }}
  {{- if .Values.mysql.enabled }}
  DATABASE_URL: {{ printf "mysql://%s:%s@%s-mysql:3306/%s" .Values.mysql.auth.username .Values.mysql.auth.password .Release.Name .Values.mysql.auth.database  | b64enc }}
  {{- else }}
  DATABASE_URL: {{ printf "pgsql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | b64enc }}
  {{- end }}
  {{- else if .Values.externalDbUrl }}
  DATABASE_URL: {{ .Values.externalDbUrl | b64enc }}
  {{- end }}
  {{- if .Values.mail.enabled }}
  MAIL_USERNAME: {{ .Values.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
  MAIL_HOST: {{ .Values.mail.host | b64enc }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.fromAddress | b64enc}}
  {{- end }}
  # .env: |
  #   APP_PORT: {{ .Values.service.port | quote | b64enc}}
  #   APP_KEY: {{ .Values.config.appKey | b64enc }}
  #   JWT_SECRET: {{ .Values.config.jwtSecret | b64enc }}
  #   CACHE_DRIVER: {{ .Values.config.cacheDriver | b64enc }}
  #   {{- if and (not .Values.sqlite.enabled) (not .Values.externalDbUrl) }}
  #   {{- if .Values.mysql.enabled }}
  #   DATABASE_URL: {{ printf "mysql://%s:%s@%s-mysql:3306/%s" .Values.mysql.auth.username .Values.mysql.auth.password .Release.Name .Values.mysql.auth.database  | b64enc }}
  #   {{- else }}
  #   DATABASE_URL: {{ printf "pgsql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | b64enc }}
  #   {{- end }}
  #   {{- else if .Values.externalDbUrl }}
  #   DATABASE_URL: {{ .Values.externalDbUrl | b64enc }}
  #   {{- end }}
  #   {{- if .Values.mail.enabled }}
  #   MAIL_USERNAME: {{ .Values.mail.username | b64enc }}
  #   MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
  #   MAIL_HOST: {{ .Values.mail.host | b64enc }}
  #   MAIL_FROM_ADDRESS: {{ .Values.mail.fromAddress | b64enc}}
  #   {{- end }}