apiVersion: v2
appVersion: 2.8.2
description: A Helm chart for Kubernetes
name: benotes
type: application
version: 0.1.0
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/charts
    condition: mysql.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/charts
    condition: postgresql.enabled
