apiVersion: v2
appVersion: 2.8.2
description: A Helm chart for Benotes application
name: benotes
type: application
version: 0.1.8
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    version: 9.16.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    version: 13.2.28
